name: build

on: [pull_request, push]

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    # Not needed until integration tests?
    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_USER: username
    #       POSTGRES_PASSWORD: password
    #       POSTGRES_DB: test_yamtga-db
    #     ports:
    #       - 5432:5432
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: |
          // required for integration tests
          yarn global add dotenv
          yarn install
      - name: Run unit tests
        run: yarn test:unit
      - name: Run integration tests
        run: yarn test:integration
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push branch tags
        uses: docker/build-push-action@v5
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yamtga-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yamtga-api:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yamtga-api:latest
      
