name: docker

on: 
  workflow_run:
    workflows:
      - "build"
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push branch tags
        uses: docker/build-push-action@v5
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yamtga-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yamtga-api:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yamtga-api:latest